services:
  blog:
    build: .
    container_name: blog-86hate
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - "traefik.http.routers.blog.rule=Host(`blog.86hate.com`)"
      - traefik.http.routers.blog.entrypoints=websecure
      - traefik.http.routers.blog.tls=true
      - traefik.http.routers.blog.tls.certresolver=letsencrypt-dns
      - traefik.http.services.blog.loadbalancer.server.port=80
    networks:
      - traefik

networks:
  traefik:
    external: true
